name: cmslpc-notebook-ci

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - cmslpc-notebook/**

jobs:
  build-and-push-cmslpc:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: cmslpc-notebook/
          push: true
          file: cmslpc-notebook/Dockerfile
          tags: mapsacosta/eafjupyter:cmslpc-notebook
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  
  build-and-push-cmslpc-dask:
    needs: build-and-push-cmslpc
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: dask-notebook/
          push: true
          file: dask-notebook/Dockerfile
          tags: mapsacosta/eafjupyter:cmslpc-dask-notebook
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
      -
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  post-build-security-scan:
    needs: [build-and-push-cmslpc, build-and-push-cmslpc-dask]
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      -
        name: Test cmslpc-notebook image for vulnerabilities
        run: |
          docker pull mapsacosta/eafjupyter:cmslpc-notebook
          docker save -o cmslpc-notebook.tar mapsacosta/eafjupyter:cmslpc-notebook
          docker pull mapsacosta/eafjupyter:cmslpc-dask-notebook
          docker save -o cmslpc-dask-notebook.tar mapsacosta/eafjupyter:cmslpc-dask-notebook
          echo "Scanning cmslpc-notebook image"
          docker run --rm -e "WORKSPACE=${PWD}" -e "FETCH_LICENSE=true" -e "ENABLE_OSS_RISK=true" -v $PWD:/app shiftleft/scan:docker scan --src /app/cmslpc-notebook.tar -o /app/reports --type docker
          echo "Scanning cmslpc-dask-notebook image"
          docker run --rm -e "WORKSPACE=${PWD}" -e "FETCH_LICENSE=true" -e "ENABLE_OSS_RISK=true" -v $PWD:/app shiftleft/scan:docker scan --src /app/cmslpc-dask-notebook.tar -o /app/reports --type docker
        env:
          NB_UID: "1000"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload report
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: reports
