name: cmslpc-gpu-notebook-ci

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - cmslpc-gpu-notebook/**

jobs:

##### GPU build breaks caching, this one has to be built from scratch every single time #####
  build-and-push-accel-ai-gpu:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: cmslpc-gpu-notebook/
          push: true
          file: cmslpc-gpu-notebook/Dockerfile
          tags: mapsacosta/eafjupyter:cmslpc-gpu-notebook
