name: scan-for-changes-in-shared-env
on:
  push:
    branches:
      - 'master'
    paths:
      - dask-notebook/**

jobs:
  check-for-modified-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get changed files using defaults
        id: changed-files
        uses: tj-actions/changed-files@v1.1.2

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: List modified file
        run: |
          echo "Report for $SHORT_SHA"
          for file in "${{ steps.changed-files.outputs.all_modified_files }}"; do
            echo "$file was modified"
          done

  open-issue-on-change:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Get changed files using defaults
        id: changed-files
        uses: tj-actions/changed-files@v1.1.2

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`<<EOF" >> $GITHUB_ENV

      - name: Export template
        id: export_first
        run: |
          cat .github/ISSUE_TEMPLATE/version-check.md dask-notebook/requirements.txt > .github/ISSUE_TEMPLATE.md ; cat .github/ISSUE_TEMPLATE.md

      - name: Opens issue for admins review if sync versions file changes
        id: open_issue_and_done
        if: contains(steps.changed-files.outputs.modified_files, 'requirements.txt')
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: .github/ISSUE_TEMPLATE.md

      - run: 'echo Created issue number ${{ steps.create-issue.outputs.number }}'
      - run: 'echo Created ${{ steps.create-issue.outputs.url }}'
