name: scan-for-changes-in-shared-env
on:
  push:
    branches:
      - 'master'
jobs:
  check-for-modified-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Get changed files using defaults
        id: changed-files
        uses: tj-actions/changed-files@v1.1.2

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV

      - name: List modified file
        run: |
          echo "Report for $SHORT_SHA"
          for file in "${{ steps.changed-files.outputs.all_modified_files }}"; do
            echo "$file was modified"
          done

  open-issue-on-change:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Get changed files using defaults
        id: changed-files
        uses: tj-actions/changed-files@v1.1.2

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`<<EOF" >> $GITHUB_ENV

      - name: Export template
        shell: bash
        run: cp .github/ISSUE_TEMPLATE/version-check.md /tmp/version-check.md && cat eaf-coffea-sync-versions >> /tmp/version-check.md && echo "ISSUE_TEMPLATE=`cat /tmp/version-check.md<<EOF`" >> $GITHUB_ENV

      - name: Verify template
        shell: bash
        run: |
          ls -ltrha ${ISSUE_TEMPLATE} && echo ${ISSUE_TEMPLATE} && cat /tmp/version-check.md

      - name: Opens issue for admins review if sync versions file changes
        if: contains(steps.changed-files.outputs.modified_files, 'eaf-coffea-sync-versions')
        uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: /tmp/version-check.md
     
      - run: 'echo Created issue number ${{ steps.create-issue.outputs.number }}'
      - run: 'echo Created ${{ steps.create-issue.outputs.url }}'
