name: scan-for-env-changes
on:
  workflow_dispatch:
    push:
      branches:
        - 'master'
      paths:
        - .github/
jobs:
  changes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get changed files using defaults
        id: changed-files
        uses: tj-actions/changed-files@v1.1.2

      - name: Run step when a file changes, in the future will open a PR.
        if: contains(steps.changed-files.outputs.modified_files, '.github/eaf-coffea-sync-versions')
        run: |
          echo "EAF-COFFEA sync file has changed."

      - name: List modified file
        run: |
          for file in "${{ steps.changed-files.outputs.all_modified_files }}"; do
            echo "$file was modified"
            cat $file
          done
